### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space due to no limit on getChildAssocs

### ISSUE THREAD

**Issue by ahmedowian** [Alfresco/alfresco-trashcan-cleaner-module#2]
For Alfresco repositories that have a lot of deleted nodes, getting all of them in one shot causes an OOME.
To avoid this problem, `TrashcanCleaner.getTrashcanChildAssocs()` should use 
```
NodeService.getChildAssocs(
            NodeRef nodeRef,
            final QNamePattern typeQNamePattern,
            final QNamePattern qnamePattern,
            final int maxResults,
            final boolean preload)
```
instead of `nodeService.getChildAssocs(archiveRoot)`

**Comment by DenisGabriela** [comment]
Issue fixed as part of [this pull request](https://github.com/Alfresco/alfresco-trashcan-cleaner-module/pull/7) and will be available with the next release (2.4-M1).
